/**
 * Every string the user can read lives here, in português de Portugal.
 * The brand is always written "Easy." — with the full stop. The only places
 * it appears without one are identifiers: file names, URL slugs, storage keys.
 */

export const BRAND = 'Easy.'

export const copy = {
  brand: BRAND,
  tagline: 'Quanto tens, mesmo, para gastar este mês.',

  nav: {
    inicio: 'Início',
    gastos: 'Gastos',
    documentos: 'Documentos',
    perfil: 'Perfil',
  },

  meses: {
    esteMes: 'Este mês',
    aDecorrer: 'A decorrer',
    fechado: (dia: string) => `Fechado a ${dia}`,
    vazioTitulo: 'Ainda não há meses guardados.',
    vazioFrase:
      'Este é o teu primeiro mês. Quando abrires a app já em outubro, setembro fica guardado aqui como está agora.',
    comoFunciona:
      'Um mês fecha na primeira vez que abres a app depois de ele virar — não à meia-noite do dia 1. Não há servidor, e nada corre com a app fechada.',
    mesFechadoTitulo: (mes: string) => `Mês novo. ${mes} ficou guardado.`,
    mesFechadoFrase: 'Não mexi em nenhum número teu. O registo fica em Todos os meses.',
    todosTitulo: 'Todos os meses',
    todos: 'Ver todos os meses',
    todosVazio: 'Ainda só há este mês.',
    todosVazioFrase:
      'Quando abrires a app já no mês seguinte, este fica guardado aqui tal como está hoje.',
    aDecorrerNota: 'ainda a decorrer',
    totalGuardado: 'Guardado ao todo',
    totalGuardadoFrase: (n: number) =>
      `em ${n} ${n === 1 ? 'mês fechado' : 'meses fechados'} — investido mais poupado`,
    colunaMes: 'Mês',
    colunaGuardado: 'Guardou',
    colunaSobras: 'Sobrou',
    verMes: 'Ver o mês',
    voltarAoMes: 'Voltar a este mês',
    dispensar: 'Está bem',
    rendimentoDoMes: 'Rendimento',
    poupadoTitulo: 'Já guardaste',
    poupadoFrase: (n: number) => `${n} ${n === 1 ? 'mês fechado' : 'meses fechados'}`,
    poupadoAte: (mes: string) => `até ${mes}`,
  },

  onboarding: {
    passo: (n: number, total: number) => `Passo ${n} de ${total}`,
    saltar: 'Saltar',
    voltar: 'Voltar',
    p1Titulo: 'Quanto recebes por mês?',
    p1Ajuda: 'O que te entra na conta, já líquido.',
    p1Continuar: 'Continuar',
    p2Titulo: 'Como queres repartir?',
    p2Ajuda: 'Escolhe um ponto de partida. Mudas quando quiseres.',
    ver: 'Ver o meu bolo.',
  },

  presets: {
    fixas: 'Fixas',
    investir: 'Investir',
    poupar: 'Poupar',
    sobras: 'Sobras',
  },

  home: {
    titulo: 'O teu bolo.',
    ola: (nome: string) => `Olá, ${nome}`,
    heroLabel: 'O teu bolo',
    heroSub: (share: string, total: string) => `${share} de ${total} que entram`,
    mesLabel: 'Por mês',
    de: (total: string) => `de ${total} que entram`,
    vazioTitulo: 'Falta dizeres quanto recebes.',
    vazioFrase: 'Escreve o rendimento e o bolo aparece.',
    vazioBotao: 'Definir rendimento',
    deficeTitulo: 'Plano em défice',
    deficeFrase: 'Estás a contar com mais do que aquilo que entra.',
    sugestoes: {
      'baixar-investimento': 'Baixa a percentagem de investimento',
      'rever-fixas': 'Revê as despesas fixas',
      'aumentar-rendimento': 'Revê o rendimento que introduziste',
    } as Record<string, string>,
    verPlano: 'Rever o plano',
  },

  legenda: {
    sobras: 'Sobras',
    fixas: 'Despesas fixas',
    gastos: 'Gastos',
    investimentos: 'Investimentos',
    poupanca: 'Poupança',
  },

  metricas: {
    titulo: 'Como está o teu mês',
    taxaPoupanca: 'Taxa de poupança',
    taxaPoupancaFrase: {
      bom: 'Guardas uma boa fatia todos os meses',
      medio: 'Dá para subir mais um pouco',
      baixo: 'Estás a guardar muito pouco',
    },
    pesoFixas: 'Peso das fixas',
    pesoFixasFrase: {
      ok: 'As tuas contas cabem bem no mês',
      alto: 'As contas fixas comem mais de metade',
    },
  },

  plano: {
    titulo: 'Plano',
    rendimento: 'Rendimento mensal',
    extras: 'Extras',
    extrasAjuda: 'Freelance, subsídios, rendas recebidas.',
    investimentos: 'Investimentos',
    poupanca: 'Poupança',
    despesas: 'Despesas fixas',
    modoPercentagem: 'Percentagem',
    modoLista: 'Lista',
    modoAjuda: 'Estimo por percentagem ou somo a tua lista de despesas.',
    verFixas: 'Ver a lista de despesas',
    limite: 'Chegaste aos 100 %. Baixa outra fatia para subir esta.',
    presetsTitulo: 'Repor um ponto de partida',
    sobrasAgora: 'Sobras',
  },

  fixas: {
    titulo: 'Despesas fixas',
    adicionar: 'Adicionar despesa',
    nome: 'Nome',
    nomePlaceholder: 'Renda, ginásio, Netflix…',
    valor: 'Valor',
    categoria: 'Categoria',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    apagar: 'Apagar',
    totalMensal: 'Total mensal',
    totalAnual: (valor: string) => `Isto são ${valor}/ano`,
    vazioTitulo: 'Ainda não tens despesas na lista.',
    vazioFrase: 'Adiciona a renda, o carro, as subscrições. Depois o bolo fica certo.',
    apagada: (valor: string) => `${valor} apagada`,
    desfazer: 'Desfazer',
    modoAviso: 'Estás no modo percentagem: esta lista não conta para o cálculo.',
    usarLista: 'Usar esta lista',
    periodicidade: 'Com que frequência',
    mensal: 'Mensal',
    anual: 'Anual',
    porAno: (valor: string) => `${valor}/ano`,
    porMes: (valor: string) => `${valor}/mês`,
  },

  categorias: {
    casa: 'Casa',
    transportes: 'Transportes',
    subscricoes: 'Subscrições',
    saude: 'Saúde',
    creditos: 'Créditos',
    outros: 'Outros',
  },

  categoriasGasto: {
    alimentacao: 'Alimentação',
    transportes: 'Transportes',
    casa: 'Casa',
    saude: 'Saúde',
    lazer: 'Lazer',
    compras: 'Compras',
    outros: 'Outros',
  },

  gastos: {
    titulo: 'Gastos',
    novo: 'Novo gasto',
    descricao: 'O que foi',
    descricaoPlaceholder: 'Jantar',
    valor: 'Quanto',
    categoria: 'Categoria',
    quando: 'Quando',
    hoje: 'Hoje',
    ontem: 'Ontem',
    guardar: 'Guardar',
    apagar: 'Apagar',
    apagado: (nome: string) => `${nome} apagado.`,
    desfazer: 'Desfazer',

    restaTitulo: 'Ainda tens para gastar',
    jaGastaste: (valor: string) => `Já gastaste ${valor} este mês`,
    semRendimento: 'Diz quanto recebes e isto passa a dizer-te quanto ainda tens.',

    vazioTitulo: 'Ainda não registaste nada.',
    vazioFrase:
      'Escreve o que gastaste — «Jantar», 19,90 € — e o número aqui em cima desce na hora.',

    totalHoje: 'Hoje',
    totalSemana: '7 dias',
    totalMes: 'Este mês',
    totalAno: 'Este ano',
    totalTudo: 'Total',

    periodos: {
      '7dias': '7 dias',
      '30dias': '30 dias',
      '12meses': '12 meses',
      anos: 'Anos',
      tudo: 'Tudo',
    },
    graficoVazio: 'Sem gastos neste período.',
    graficoDescricao: (periodo: string, total: string) =>
      `Gráfico de linhas dos gastos, ${periodo}. Total ${total}.`,
    media: (valor: string) => `média de ${valor}`,
    maximo: (valor: string) => `máximo ${valor}`,

    porCategoria: 'Por categoria',
    semCategorias: 'As categorias aparecem quando registares o primeiro gasto.',
    limiteDe: (valor: string) => `de ${valor}`,
    restam: (valor: string) => `restam ${valor}`,
    acima: (valor: string) => `${valor} acima do limite`,
    definirLimite: 'Limite mensal',
    limiteAjuda: 'Deixa a zero para não teres limite nesta categoria.',
    semLimite: 'Sem limite',
    guardarLimite: 'Guardar limite',

    // A apresentação de um gasto, e a fatura lá dentro.
    detalhe: 'Gasto',
    fatura: 'Fatura',
    anexarFatura: 'Anexar fatura',
    semFaturaAjuda: 'Tira uma fotografia ao talão ou escolhe um PDF. Fica no telemóvel, como tudo o resto.',
    faturaPorAnexar: (nome: string) => `${nome} — anexa quando guardares`,
    tirarFatura: 'Tirar do gasto',
    substituirFatura: 'Trocar',
    descarregarFatura: 'Descarregar',
    faturaEmFalta:
      'O ficheiro desta fatura não está neste telemóvel. Acontece quando o orçamento foi importado de outro sítio — os ficheiros não viajam no JSON.',
    faturaSemPreVisualizacao: 'Este tipo de ficheiro não se pré-visualiza aqui. Descarrega para o abrir.',
    aAnexar: 'A anexar…',
    temFatura: 'Com fatura',

    fixasTitulo: 'Despesas fixas',
    fixasFrase: (valor: string) => `${valor} por mês, sempre as mesmas`,
    fixasNota: 'Já estão descontadas. Não é preciso registá-las aqui.',
    verFixas: 'Ver as despesas fixas',
    verMeses: 'Ver todos os meses',
  },

  investir: {
    titulo: 'Investir',
    fundoAvisoTitulo: 'Antes de investir',
    fundoAviso: '6 meses de despesas em fundo de emergência.',
    fundoEstado: (meses: string) => `Estás em ${meses} meses.`,
    fundoCompleto: 'Já tens os 6 meses cobertos.',
    aInvestir: (valor: string) => `Estás a investir ${valor}/mês`,
    daoEm: (anos: number, valor: string) => `Ao fim de ${anos} anos dão ${valor}`,
    simulador: 'Simulador de juro composto',
    porMes: 'Por mês',
    taxaAnual: 'Taxa anual',
    anos: 'Anos',
    resultado: 'Ao fim do prazo',
    capital: 'O que entregaste',
    juro: 'O que rendeu',
    opcoes: 'Onde se pode pôr o dinheiro',
    risco: 'Risco',
    horizonte: 'Horizonte',
    liquidez: 'Liquidez',
    disclaimer:
      'A Easy. é uma ferramenta de organização pessoal. Não presta aconselhamento financeiro, fiscal ou de investimento. Os valores apresentados são estimativas.',
  },

  documentos: {
    titulo: 'Documentos',
    adicionar: 'Adicionar ficheiros',
    largar: 'Larga aqui os ficheiros',
    vazioTitulo: 'Ainda não tens nada guardado.',
    vazioFrase:
      'Guarda aqui o contrato de arrendamento, o seguro do carro, o IRS. Fica tudo no teu telemóvel.',
    aviso: 'Os documentos ficam só neste dispositivo. Se limpares os dados do browser, perdem-se.',
    exportar: 'Exportar tudo',
    aExportar: 'A preparar o ficheiro…',
    abrir: 'Abrir',
    descarregar: 'Descarregar',
    apagar: 'Apagar',
    semPreVisualizacao: 'Este tipo de ficheiro não se pré-visualiza aqui.',
    apagado: (nome: string) => `${nome} apagado`,
    desfazer: 'Desfazer',
  },

  conta: {
    criarTitulo: 'Cria o teu perfil',
    criarFrase: 'Só o nome. Fica neste telemóvel, não há conta nem servidor.',
    nome: 'Nome',
    nomePlaceholder: 'Como te chamas',
    criar: 'Criar perfil',
    membroDesde: (mes: string) => `Membro desde ${mes}`,
    resumo: (rendimento: string, reparticao: string) => `${rendimento}/mês · ${reparticao}`,
    semRendimento: 'Ainda sem rendimento definido',
    foto: 'Foto de perfil',
    mudarFoto: 'Mudar foto',
    apagarFoto: 'Remover foto',
    dados: 'Dados pessoais',
    dadosAjuda: 'A app não usa nada disto para calcular. Fica aqui para o teres à mão.',
    email: 'Email',
    telemovel: 'Telemóvel',
    nascimento: 'Data de nascimento',
    nif: 'NIF',
    guardar: 'Guardar',
    guardado: 'Guardado.',
    seguranca: 'Bloqueio',
    pin: 'PIN de 4 dígitos',
    pinAjuda:
      'Tranca a app neste telemóvel. Não cifra nada: quem tiver o telemóvel desbloqueado e as ferramentas do browser abertas chega aos dados na mesma.',
    definirPin: 'Definir PIN',
    mudarPin: 'Mudar PIN',
    removerPin: 'Remover PIN',
    pinNovo: 'Escolhe um PIN',
    pinRepetir: 'Repete o PIN',
    pinDiferente: 'Os dois PIN não são iguais.',
    pinIndisponivel: 'Este browser não permite guardar um PIN em segurança.',
    sair: 'Terminar sessão',
    sairSemPin: 'Define um PIN para poderes trancar a app.',
    entrar: 'Introduz o teu PIN',
    errado: 'PIN errado.',
    esqueci: 'Esqueci-me do PIN',
    esqueciAviso:
      'Não há forma de o recuperar: não existe servidor nem email de reposição. A única saída é apagar o perfil, o orçamento e os documentos deste telemóvel.',
    esqueciBotao: 'Apagar tudo e recomeçar',
    apagarPerfil: 'Apagar perfil',
    apagarPerfilAviso: 'Apaga o nome, a foto, os dados e o PIN. O orçamento e os documentos ficam.',
  },

  perfil: {
    titulo: 'Perfil',
    plano: 'Plano',
    rendimento: 'Rendimento',
    repartir: 'Repartição',
    fixas: 'Despesas fixas',
    fixasLista: (n: number) => `${n} na lista`,
    fixasPercentagem: 'Por percentagem',
    investir: 'Investir',
    discreto: 'Modo discreto',
    discretoAjuda: 'Esconde os valores em euros. A repartição continua à vista.',
    tema: 'Tema',
    temaAuto: 'Automático',
    temaClaro: 'Claro',
    temaEscuro: 'Escuro',
    dados: 'Os teus dados',
  },

  definicoes: {
    titulo: 'Os teus dados',
    poupancaAcumulada: 'Poupança já acumulada',
    poupancaAcumuladaAjuda: 'O que já tens de lado. Serve para o fundo de emergência.',
    dados: 'Os teus dados',
    exportar: 'Exportar orçamento (JSON)',
    importar: 'Importar orçamento (JSON)',
    importarErro: 'Não consegui ler esse ficheiro.',
    importarOk: 'Orçamento importado.',
    apagar: 'Apagar tudo',
    apagarAviso: 'Isto apaga o orçamento e os documentos deste dispositivo. Não há volta atrás.',
    apagarConfirma: 'Escreve APAGAR para confirmar',
    apagarPalavra: 'APAGAR',
    apagarBotao: 'Apagar definitivamente',
    versao: 'Versão',
    ondeFicam: 'Tudo fica neste dispositivo. A Easy. não usa contas nem servidores.',
  },

  comum: {
    fechar: 'Fechar',
    voltar: 'Voltar',
    definicoes: 'Definições',
    meses: 'meses',
  },
} as const

export const OPCOES_INVESTIMENTO = [
  {
    id: 'certificados',
    nome: 'Certificados de Aforro',
    risco: 1,
    horizonte: 'Médio prazo',
    liquidez: 'Alta, com penalização no início',
    frase: 'Dívida do Estado português, feita para pequenos aforradores.',
  },
  {
    id: 'depositos',
    nome: 'Depósitos a prazo',
    risco: 1,
    horizonte: 'Curto prazo',
    liquidez: 'Alta',
    frase: 'O banco garante o capital e paga juros combinados à partida.',
  },
  {
    id: 'ppr',
    nome: 'PPR',
    risco: 2,
    horizonte: 'Longo prazo',
    liquidez: 'Baixa até à reforma',
    frase: 'Poupança para a reforma, com benefícios fiscais e regras de saída.',
  },
  {
    id: 'etf',
    nome: 'ETF de índice global',
    risco: 4,
    horizonte: 'Longo prazo',
    liquidez: 'Alta',
    frase: 'Segue um índice mundial de ações. Oscila, e recupera com tempo.',
  },
  {
    id: 'risco',
    nome: 'Ativos de risco elevado',
    risco: 5,
    horizonte: 'Indefinido',
    liquidez: 'Variável',
    frase: 'Pode valorizar muito ou perder tudo. Só com dinheiro que te sobra.',
  },
] as const

export const PRESETS = [
  {
    id: 'equilibrado',
    nome: 'Equilibrado',
    frase: 'Um meio-termo confortável.',
    fixas: 50,
    investimentos: 10,
    poupanca: 10,
    sobras: 30,
  },
  {
    id: 'poupador',
    nome: 'Poupador',
    frase: 'Guardas mais, gastas menos.',
    fixas: 50,
    investimentos: 20,
    poupanca: 10,
    sobras: 20,
  },
  {
    id: 'tranquilo',
    nome: 'Tranquilo',
    frase: 'Mais folga ao fim do mês.',
    fixas: 55,
    investimentos: 5,
    poupanca: 5,
    sobras: 35,
  },
] as const

export type Preset = (typeof PRESETS)[number]
